### ISSUE TITLE
Hyphen spacing off with surround letter characters

### ISSUE THREAD

**Issue by demoy** [xconsau/Cause-Old#1]
![Screenshot from 2024-04-20 08-25-55](https://github.com/xconsau/Cause/assets/2396524/05228b65-542f-48fb-bc9a-264a09d7fee8)

The hyphen are being merges into the surrounding characters. 

System Environment details
Operating System/Desktop Environemnt: Linux/Fedora 38
Browser Tested: Firefox

**Comment by xconsau** [comment]
Hello @demoy,

Thank you for reporting the issue. It seems like the hypen's advanced width is either set to zero or it has a large negative kerning. This is happening after compilation with Fontmake. When I export via FontLab, the hyphen works correctly. See the [Cause-VF.ttf ](https://github.com/xconsau/Cause/blob/main/fonts/variable/Cause-VF.ttf)file.

**Comment by demoy** [comment]
Yes that fixed it. Thank you.
